language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t khoadd6-udagram-simple-express .
  - docker tag khoadd6-udagram-simple-express dinhdangkhoa0201/khoadd6-udagram-simple-express:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dinhdangkhoa0201/khoadd6-udagram-simple-express

